# Generated by Django 4.2 on 2023-04-30 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(blank=True, max_length=30, null=True)),
                ("count", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Descriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="NodeSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target1", models.CharField(max_length=100)),
                ("target2", models.CharField(max_length=100)),
                ("similarity", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Gwas",
            fields=[
                (
                    "nodesimilarity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.nodesimilarity",
                    ),
                ),
            ],
            bases=("search.nodesimilarity",),
        ),
        migrations.CreateModel(
            name="Hgene",
            fields=[
                (
                    "nodesimilarity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.nodesimilarity",
                    ),
                ),
            ],
            bases=("search.nodesimilarity",),
        ),
        migrations.CreateModel(
            name="Hprotein",
            fields=[
                (
                    "nodesimilarity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.nodesimilarity",
                    ),
                ),
            ],
            bases=("search.nodesimilarity",),
        ),
        migrations.CreateModel(
            name="Intact",
            fields=[
                (
                    "nodesimilarity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.nodesimilarity",
                    ),
                ),
            ],
            bases=("search.nodesimilarity",),
        ),
        migrations.CreateModel(
            name="MousePheno",
            fields=[
                (
                    "nodesimilarity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.nodesimilarity",
                    ),
                ),
            ],
            bases=("search.nodesimilarity",),
        ),
        migrations.CreateModel(
            name="Pathway",
            fields=[
                (
                    "nodesimilarity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.nodesimilarity",
                    ),
                ),
            ],
            bases=("search.nodesimilarity",),
        ),
        migrations.CreateModel(
            name="Reactome",
            fields=[
                (
                    "nodesimilarity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.nodesimilarity",
                    ),
                ),
            ],
            bases=("search.nodesimilarity",),
        ),
        migrations.CreateModel(
            name="Signor",
            fields=[
                (
                    "nodesimilarity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.nodesimilarity",
                    ),
                ),
            ],
            bases=("search.nodesimilarity",),
        ),
    ]
