# Generated by Django 4.1.7 on 2023-03-30 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="descriptors",
            old_name="descriptors",
            new_name="descriptor",
        ),
    ]
