# Generated by Django 4.1.7 on 2023-03-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_rename_descriptors_descriptors_descriptor"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Descriptors",
            new_name="Descriptor",
        ),
        migrations.RenameField(
            model_name="descriptor",
            old_name="descriptor",
            new_name="descriptor_name",
        ),
    ]
