# Generated by Django 4.1.7 on 2023-04-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
    ]
