# Generated by Django 4.1.7 on 2023-04-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0005_adverseevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdverseEvent",
        ),
        migrations.DeleteModel(
            name="Target",
        ),
    ]
