# Generated by Django 4.1.7 on 2023-04-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0006_delete_adverseevent_delete_target"),
    ]

    operations = [
        migrations.RenameField(
            model_name="descriptor",
            old_name="descriptor_name",
            new_name="name",
        ),
    ]
