# Generated by Django 4.2 on 2023-04-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0008_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="action",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
